#!/bin/bash

#!/usr/bin/bash 

file=$1
base=`basename $1`
stem="${base%.*}"
src="${stem}.py"
url=$2

cat<<EOF

<small>_This file is part of LEANER. To know more, download [$src]($url/$file)'s source or read our [home](https://github.com/ai-se/leaner) page._</small>


EOF
cat $1 |
gawk --source '
BEGIN { First = 1
        In = 1}
/^"""</,/^>"""/ { next }

/^"""/ { In = 1 - In
         if (In) 
	     print "````python"
         else
	     if (First)
               First = 0
             else
               print "````"
         next
       }
! First { print $0 }
END { if (In) print "````" }
' 
 

