mixu-gray:
	generate-md --layout mixu-gray --input ./ --output ./

github:
	generate-md --layout github --input ./ --output ./

install:
	sudo apt-get install pandoc
	sudo npm install -g markdown-styles
