mine     :; generate-md --layout ./my-layout/page.html --input ./ --output ./
boot     :; generate-md --layout bootstrap3     --input ./ --output ./
book     :; generate-md --layout mixu-book      --input ./ --output ./
gray     :; generate-md --layout mixu-gray      --input ./ --output ./
github   :; generate-md --layout github         --input ./ --output ./
mixu     :; generate-md --layout mixu-bootstrap --input ./ --output ./

install:
	sudo apt-get install pandoc
	sudo npm install -g markdown-styles
